"""baseline_current_schema

Revision ID: 20260730_01
Revises:
Create Date: 2026-07-30 15:20:33.804105
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260730_01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=160), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('schedule', sa.Text(), nullable=True),
    sa.Column('maps_url', sa.Text(), nullable=True),
    sa.Column('instagram_url', sa.Text(), nullable=True),
    sa.Column('reviews_url', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('secondary_color', sa.String(length=20), nullable=True),
    sa.Column('accent_color', sa.String(length=20), nullable=True),
    sa.Column('background_color', sa.String(length=20), nullable=True),
    sa.Column('theme_key', sa.String(length=40), nullable=True),
    sa.Column('template_key', sa.String(length=40), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('logo_alt', sa.String(length=240), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('picture_url', sa.String(length=1000), nullable=True),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('preferred_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=True),
    sa.Column('resource_id', sa.String(length=120), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('availability_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('windows_json', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_exceptions_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_exceptions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_exceptions_id'), ['id'], unique=False)

    op.create_table('availability_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('slot_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_between_bookings_minutes', sa.Integer(), nullable=False),
    sa.Column('min_notice_minutes', sa.Integer(), nullable=False),
    sa.Column('max_days_ahead', sa.Integer(), nullable=False),
    sa.Column('weekly_schedule_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_settings_business_id'), ['business_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_availability_settings_id'), ['id'], unique=False)

    op.create_table('blocked_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocked_dates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocked_dates_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocked_dates_id'), ['id'], unique=False)

    op.create_table('business_channel_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=False),
    sa.Column('external_account_name', sa.String(length=255), nullable=True),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('encryption_key_version', sa.String(length=60), nullable=True),
    sa.Column('token_type', sa.String(length=40), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('token_last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('granted_scopes_json', sa.Text(), nullable=True),
    sa.Column('integration_status', sa.String(length=30), nullable=False),
    sa.Column('provider_status', sa.String(length=80), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('last_error_subcode', sa.String(length=80), nullable=True),
    sa.Column('last_error_type', sa.String(length=120), nullable=True),
    sa.Column('safe_error_message', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("integration_status IN ('pending','connected','degraded','expired','disconnected','revoked','error')", name='ck_channel_integration_status'),
    sa.CheckConstraint('(encrypted_access_token IS NULL AND encryption_key_version IS NULL) OR (encrypted_access_token IS NOT NULL AND encryption_key_version IS NOT NULL)', name='ck_channel_integration_encrypted_token_version'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'provider', name='uq_channel_integration_business_provider'),
    sa.UniqueConstraint('provider', 'external_account_id', name='uq_channel_integration_provider_account')
    )
    with op.batch_alter_table('business_channel_integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_channel_integrations_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_channel_integrations_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_channel_integrations_encryption_key_version'), ['encryption_key_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_channel_integrations_external_account_id'), ['external_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_channel_integrations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_channel_integrations_integration_status'), ['integration_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_channel_integrations_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_channel_integrations_token_expires_at'), ['token_expires_at'], unique=False)
        batch_op.create_index('ix_channel_integrations_business_provider', ['business_id', 'provider'], unique=False)
        batch_op.create_index('ix_channel_integrations_provider_account_status', ['provider', 'external_account_id', 'integration_status'], unique=False)

    op.create_table('business_gallery_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.String(length=240), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_gallery_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_gallery_images_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_gallery_images_id'), ['id'], unique=False)

    op.create_table('business_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('public_name', sa.String(length=200), nullable=True),
    sa.Column('bookable', sa.Boolean(), nullable=False),
    sa.Column('show_schedule', sa.Boolean(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'user_id', name='uq_business_user')
    )
    with op.batch_alter_table('business_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_users_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_users_user_id'), ['user_id'], unique=False)

    op.create_table('conversation_automation_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('automation_enabled', sa.Boolean(), nullable=False),
    sa.Column('monthly_auto_limit', sa.Integer(), nullable=False),
    sa.Column('auto_used_current_period', sa.Integer(), nullable=False),
    sa.Column('included_credits_per_period', sa.Integer(), nullable=False),
    sa.Column('included_credits_used', sa.Integer(), nullable=False),
    sa.Column('additional_credits_balance', sa.Integer(), nullable=False),
    sa.Column('period_yyyymm', sa.String(length=7), nullable=False),
    sa.Column('period_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_status', sa.String(length=30), nullable=False),
    sa.Column('on_limit_reached', sa.String(length=30), nullable=False),
    sa.Column('auto_threshold', sa.Integer(), nullable=False),
    sa.Column('human_reply_pause_minutes', sa.Integer(), nullable=False),
    sa.Column('plan_key', sa.String(length=60), nullable=True),
    sa.Column('automation_feature_enabled', sa.Boolean(), nullable=False),
    sa.Column('instagram_channel_enabled', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_channel_enabled', sa.Boolean(), nullable=False),
    sa.Column('allowed_limit_behaviors_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_automation_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_automation_settings_business_id'), ['business_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_conversation_automation_settings_id'), ['id'], unique=False)

    op.create_table('conversation_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_conversation_template_name')
    )
    with op.batch_alter_table('conversation_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_templates_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_templates_id'), ['id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'phone', name='uq_customer_business_phone')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=False)

    op.create_table('google_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('cluster_name', sa.String(length=120), nullable=True),
    sa.Column('gcp_project_id', sa.String(length=200), nullable=True),
    sa.Column('service_account_email', sa.String(length=300), nullable=True),
    sa.Column('credentials_ref', sa.Text(), nullable=True),
    sa.Column('calendar_id', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('last_successful_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('google_integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_integrations_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_google_integrations_id'), ['id'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_text', sa.String(length=80), nullable=True),
    sa.Column('duration_text', sa.String(length=80), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_service_business_name')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_id'), ['id'], unique=False)

    op.create_table('weekly_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('slots_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_availability_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_availability_id'), ['id'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_user_id', sa.Integer(), nullable=True),
    sa.Column('customer_email', sa.String(length=320), nullable=True),
    sa.Column('public_manage_token', sa.String(length=255), nullable=True),
    sa.Column('created_by_user', sa.Boolean(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('staff_business_user_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=200), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('preferred_date', sa.String(length=20), nullable=True),
    sa.Column('preferred_day_label', sa.String(length=100), nullable=True),
    sa.Column('preferred_time', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('google_calendar_event_id', sa.String(length=300), nullable=True),
    sa.Column('google_sync_status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_business_user_id'], ['business_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_customer_email'), ['customer_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_customer_user_id'), ['customer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_public_manage_token'), ['public_manage_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookings_staff_business_user_id'), ['staff_business_user_id'], unique=False)

    op.create_table('business_user_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_user_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('windows_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_user_id'], ['business_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_user_id', 'weekday', name='uq_business_user_availability_day')
    )
    with op.batch_alter_table('business_user_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_user_availability_business_user_id'), ['business_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_user_availability_id'), ['id'], unique=False)

    op.create_table('business_user_availability_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('windows_json', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_user_id'], ['business_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_user_id', 'date', name='uq_business_user_availability_exception_date')
    )
    with op.batch_alter_table('business_user_availability_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_user_availability_exceptions_business_user_id'), ['business_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_user_availability_exceptions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_user_availability_exceptions_id'), ['id'], unique=False)

    op.create_table('business_user_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_user_id'], ['business_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_user_id', 'service_id', name='uq_business_user_service')
    )
    with op.batch_alter_table('business_user_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_user_services_business_user_id'), ['business_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_user_services_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_user_services_service_id'), ['service_id'], unique=False)

    op.create_table('conversation_automation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.String(length=60), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['conversation_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'intent', name='uq_conversation_automation_rule')
    )
    with op.batch_alter_table('conversation_automation_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_automation_rules_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_automation_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_automation_rules_template_id'), ['template_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('external_conversation_id', sa.String(length=255), nullable=True),
    sa.Column('external_user_id', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=40), nullable=True),
    sa.Column('customer_username', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_message_text', sa.Text(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('last_inbound_at', sa.DateTime(), nullable=True),
    sa.Column('last_outbound_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_business_user_id', sa.Integer(), nullable=True),
    sa.Column('detected_intent', sa.String(length=60), nullable=True),
    sa.Column('intent_confidence', sa.Integer(), nullable=True),
    sa.Column('matched_patterns_json', sa.Text(), nullable=True),
    sa.Column('automation_mode', sa.String(length=20), nullable=False),
    sa.Column('automation_paused_until', sa.DateTime(), nullable=True),
    sa.Column('automation_pause_reason', sa.String(length=60), nullable=True),
    sa.Column('automation_pause_updated_by', sa.Integer(), nullable=True),
    sa.Column('automation_pause_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_business_user_id'], ['business_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'channel', 'external_user_id', name='uq_conversation_external_user')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_assigned_business_user_id'), ['assigned_business_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_automation_paused_until'), ['automation_paused_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_detected_intent'), ['detected_intent'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_external_user_id'), ['external_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_last_message_at'), ['last_message_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_status'), ['status'], unique=False)

    op.create_table('system_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_key', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=40), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('provider_error_code', sa.String(length=80), nullable=True),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_occurred_at', sa.DateTime(), nullable=False),
    sa.Column('last_occurred_at', sa.DateTime(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('safe_details_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['integration_id'], ['business_channel_integrations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_incidents_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_first_occurred_at'), ['first_occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_incident_key'), ['incident_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_system_incidents_integration_id'), ['integration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_last_occurred_at'), ['last_occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_notified_at'), ['notified_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_operation'), ['operation'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_provider_error_code'), ['provider_error_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_resolved_at'), ['resolved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_status'), ['status'], unique=False)

    op.create_table('booking_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('stored_filename', sa.String(length=300), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_attachments_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_attachments_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_attachments_id'), ['id'], unique=False)

    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('sender_type', sa.String(length=30), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('delivery_status', sa.String(length=30), nullable=True),
    sa.Column('raw_payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_messages_provider_message_id'), ['provider_message_id'], unique=False)

    op.create_table('review_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_phone', sa.String(length=40), nullable=True),
    sa.Column('reviews_url', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('copied_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', name='uq_review_requests_booking_id')
    )
    with op.batch_alter_table('review_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_requests_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_requests_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_requests_id'), ['id'], unique=False)

    op.create_table('sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('operation', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_jobs_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_jobs_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_jobs_id'), ['id'], unique=False)

    op.create_table('automation_credit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('included_delta', sa.Integer(), nullable=False),
    sa.Column('additional_delta', sa.Integer(), nullable=False),
    sa.Column('included_balance_after', sa.Integer(), nullable=False),
    sa.Column('additional_balance_after', sa.Integer(), nullable=False),
    sa.Column('total_balance_after', sa.Integer(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_method', sa.String(length=60), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('external_reference', sa.String(length=120), nullable=True),
    sa.Column('related_message_id', sa.Integer(), nullable=True),
    sa.Column('period_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('safe_metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_message_id'], ['conversation_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'idempotency_key', name='uq_automation_credit_business_idempotency'),
    sa.UniqueConstraint('related_message_id', name='uq_automation_credit_related_message')
    )
    with op.batch_alter_table('automation_credit_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_automation_credit_business_created', ['business_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_credit_transactions_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_credit_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_credit_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_credit_transactions_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_credit_transactions_related_message_id'), ['related_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_credit_transactions_transaction_type'), ['transaction_type'], unique=False)

    op.create_table('conversation_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('intent', sa.String(length=60), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['conversation_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_suggestions_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_suggestions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_suggestions_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_suggestions_status'), ['status'], unique=False)

    op.create_table('message_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('review_request_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_phone', sa.String(length=40), nullable=True),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('message_type', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('whatsapp_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('skipped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_request_id'], ['review_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'booking_id', 'message_type', name='uq_message_outbox_booking_event')
    )
    with op.batch_alter_table('message_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_outbox_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_outbox_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_outbox_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_outbox_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_outbox_review_request_id'), ['review_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_outbox_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError(
        "El downgrade de la baseline eliminaría todo el esquema. "
        "Restaure un backup validado en lugar de ejecutar esta operación."
    )


def _unsafe_generated_downgrade_reference_only() -> None:
    """Generated teardown retained only as schema review evidence; never called."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_outbox_status'))
        batch_op.drop_index(batch_op.f('ix_message_outbox_review_request_id'))
        batch_op.drop_index(batch_op.f('ix_message_outbox_message_type'))
        batch_op.drop_index(batch_op.f('ix_message_outbox_id'))
        batch_op.drop_index(batch_op.f('ix_message_outbox_business_id'))
        batch_op.drop_index(batch_op.f('ix_message_outbox_booking_id'))

    op.drop_table('message_outbox')
    with op.batch_alter_table('conversation_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_conversation_suggestions_message_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_suggestions_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_suggestions_conversation_id'))

    op.drop_table('conversation_suggestions')
    with op.batch_alter_table('automation_credit_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_credit_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_automation_credit_transactions_related_message_id'))
        batch_op.drop_index(batch_op.f('ix_automation_credit_transactions_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_automation_credit_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_automation_credit_transactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_automation_credit_transactions_business_id'))
        batch_op.drop_index('ix_automation_credit_business_created')

    op.drop_table('automation_credit_transactions')
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_sync_jobs_business_id'))
        batch_op.drop_index(batch_op.f('ix_sync_jobs_booking_id'))

    op.drop_table('sync_jobs')
    with op.batch_alter_table('review_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_requests_id'))
        batch_op.drop_index(batch_op.f('ix_review_requests_business_id'))
        batch_op.drop_index(batch_op.f('ix_review_requests_booking_id'))

    op.drop_table('review_requests')
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_messages_provider_message_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_messages_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_conversation_messages_conversation_id'))

    op.drop_table('conversation_messages')
    with op.batch_alter_table('booking_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_attachments_id'))
        batch_op.drop_index(batch_op.f('ix_booking_attachments_business_id'))
        batch_op.drop_index(batch_op.f('ix_booking_attachments_booking_id'))

    op.drop_table('booking_attachments')
    with op.batch_alter_table('system_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_resolved_at'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_provider_error_code'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_provider'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_operation'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_notified_at'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_message_id'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_last_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_integration_id'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_incident_key'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_id'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_first_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_channel'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_category'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_business_id'))

    op.drop_table('system_incidents')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_status'))
        batch_op.drop_index(batch_op.f('ix_conversations_last_message_at'))
        batch_op.drop_index(batch_op.f('ix_conversations_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_external_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_detected_intent'))
        batch_op.drop_index(batch_op.f('ix_conversations_channel'))
        batch_op.drop_index(batch_op.f('ix_conversations_business_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_automation_paused_until'))
        batch_op.drop_index(batch_op.f('ix_conversations_assigned_business_user_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('conversation_automation_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_automation_rules_template_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_automation_rules_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_automation_rules_business_id'))

    op.drop_table('conversation_automation_rules')
    with op.batch_alter_table('business_user_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_user_services_service_id'))
        batch_op.drop_index(batch_op.f('ix_business_user_services_id'))
        batch_op.drop_index(batch_op.f('ix_business_user_services_business_user_id'))

    op.drop_table('business_user_services')
    with op.batch_alter_table('business_user_availability_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_user_availability_exceptions_id'))
        batch_op.drop_index(batch_op.f('ix_business_user_availability_exceptions_date'))
        batch_op.drop_index(batch_op.f('ix_business_user_availability_exceptions_business_user_id'))

    op.drop_table('business_user_availability_exceptions')
    with op.batch_alter_table('business_user_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_user_availability_id'))
        batch_op.drop_index(batch_op.f('ix_business_user_availability_business_user_id'))

    op.drop_table('business_user_availability')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_staff_business_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_public_manage_token'))
        batch_op.drop_index(batch_op.f('ix_bookings_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_customer_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_customer_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_customer_email'))
        batch_op.drop_index(batch_op.f('ix_bookings_business_id'))

    op.drop_table('bookings')
    with op.batch_alter_table('weekly_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_availability_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_availability_business_id'))

    op.drop_table('weekly_availability')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_id'))
        batch_op.drop_index(batch_op.f('ix_services_business_id'))

    op.drop_table('services')
    with op.batch_alter_table('google_integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_integrations_id'))
        batch_op.drop_index(batch_op.f('ix_google_integrations_business_id'))

    op.drop_table('google_integrations')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_id'))
        batch_op.drop_index(batch_op.f('ix_customers_business_id'))

    op.drop_table('customers')
    with op.batch_alter_table('conversation_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_templates_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_templates_business_id'))

    op.drop_table('conversation_templates')
    with op.batch_alter_table('conversation_automation_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_automation_settings_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_automation_settings_business_id'))

    op.drop_table('conversation_automation_settings')
    with op.batch_alter_table('business_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_business_users_id'))
        batch_op.drop_index(batch_op.f('ix_business_users_business_id'))

    op.drop_table('business_users')
    with op.batch_alter_table('business_gallery_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_gallery_images_id'))
        batch_op.drop_index(batch_op.f('ix_business_gallery_images_business_id'))

    op.drop_table('business_gallery_images')
    with op.batch_alter_table('business_channel_integrations', schema=None) as batch_op:
        batch_op.drop_index('ix_channel_integrations_provider_account_status')
        batch_op.drop_index('ix_channel_integrations_business_provider')
        batch_op.drop_index(batch_op.f('ix_business_channel_integrations_token_expires_at'))
        batch_op.drop_index(batch_op.f('ix_business_channel_integrations_provider'))
        batch_op.drop_index(batch_op.f('ix_business_channel_integrations_integration_status'))
        batch_op.drop_index(batch_op.f('ix_business_channel_integrations_id'))
        batch_op.drop_index(batch_op.f('ix_business_channel_integrations_external_account_id'))
        batch_op.drop_index(batch_op.f('ix_business_channel_integrations_encryption_key_version'))
        batch_op.drop_index(batch_op.f('ix_business_channel_integrations_channel'))
        batch_op.drop_index(batch_op.f('ix_business_channel_integrations_business_id'))

    op.drop_table('business_channel_integrations')
    with op.batch_alter_table('blocked_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocked_dates_id'))
        batch_op.drop_index(batch_op.f('ix_blocked_dates_business_id'))

    op.drop_table('blocked_dates')
    with op.batch_alter_table('availability_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_settings_id'))
        batch_op.drop_index(batch_op.f('ix_availability_settings_business_id'))

    op.drop_table('availability_settings')
    with op.batch_alter_table('availability_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_exceptions_id'))
        batch_op.drop_index(batch_op.f('ix_availability_exceptions_date'))
        batch_op.drop_index(batch_op.f('ix_availability_exceptions_business_id'))

    op.drop_table('availability_exceptions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_business_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_slug'))
        batch_op.drop_index(batch_op.f('ix_businesses_id'))

    op.drop_table('businesses')
    # ### end Alembic commands ###
